name: SonarCloud Scan

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Print PATH environment variable
        run: echo $PATH
     
